platform :ios, '9.0'

target 'Flickr Viewer' do
  use_frameworks!

  # Pods for Flickr Viewer

  target 'Flickr ViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Flickr ViewerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
